### ISSUE TITLE
Sorted groups issue on sorting of column

### ISSUE THREAD

**Issue by AndrewZagovora** [SenyaMur/ag-grid-odata#14]
To replicate use the Server-Side model

Steps to replicate:
1. Group data by some column
2. Apply the sorting to group by clicking the label of the Group column
3. Open one of collapsed groups
4. Try to sort by any different field

Expected result:
The data is sorted, sorting of groups remains the same.

Actual Result:
Group is collapsed, group column is not sorted.

Applicable to the case when 2 or more groups are opened.

**Comment by SenyaMur** [comment]
Hi @AndrewZagovora. I reporoduced your issue.  
When do 4 step, then sorted only choosed field (i.e. grouped columns excluded from sorting)
New query get?$top=100&$apply=groupby((GroupColumn)),aggregate($count%20as%20childCount))&$orderBy=TheClickedFild
And then return Exception for new query:
`The query specified in the URI is not valid. $apply/groupby grouping expression 'TheClickedFild' must evaluate to a property access value.`

You can sort columns only which contained in groupby or aggregate. Otherwise you catch exception (see above).
I can filter sort columns which contained in  groupby or aggregate

**Comment by AndrewZagovora** [comment]
I see, thank you. But can you fix the following:

1. Some column is grouped.
2. One or more groups in the group column are expanded
3. I am clicking on grouped column title to apply group sorting

ER: The group column is sorted, the expanded groups still expanded

AR: The group column is sorted, all the groups are collapsed

**Comment by SenyaMur** [comment]
> ER: The group column is sorted, the expanded groups still expanded
I can't reproduce it. If I do your steps then on 3 step the grid will call new request and all groups will collapsed.

Can you show your the described situation?

**Comment by AndrewZagovora** [comment]
1. Group by column
![example  (3)](https://user-images.githubusercontent.com/32092177/106479158-acbdac80-64b2-11eb-8018-a090659f3a2d.png)

2. Apply sorting and open one group
![example  (2)](https://user-images.githubusercontent.com/32092177/106479228-be9f4f80-64b2-11eb-823e-c6ceba3462e8.png)

3. Apply sorting on group column again
![example  (1)](https://user-images.githubusercontent.com/32092177/106479260-cc54d500-64b2-11eb-9383-b8c3126dbda7.png)

As you can see, the opened group is closed. It closes after the sorting.
Pls let me know if you need any further information.

**Comment by SenyaMur** [comment]
Thank you for explain. 
I can't change ag-grid behaviour. ag-grid-odata just build query.
